### ISSUE TITLE
option to set wallpaper size and adjustment

### ISSUE THREAD

**Issue by phaleintx** [neffo/earth-view-wallpaper-gnome-extension#11]
This is a fantastic extension.  I have a dual monitor setup and I was wondering if there was a way to set a default wallpaper size, say like 3240x1080 and set the wallpaper adjustment to "wallpaper" as it is in the gnome tweaks utility.  This would allow the downloaded wallpaper to fit the dual screen.

**Comment by neffo** [comment]
Thanks @phaleintx I appreciate the kind words!

I only have the one screen at the moment. How does it differ from 'zoom'? Does setting it as 'wallpaper' mean the picture get stretched over both displays?

**Comment by phaleintx** [comment]
Hello! As long as you've got a wallpaper that is sized to the full screen size "spanned desktop" then "wallpaper" fits across both and doesn't stretch.  So on my home computer I have 2 x 24" 1920x1080 monitors.  The total screen size is 3240x1080.  If the image I download is that size or bigger, the "wallpaper" setting sets it to fill across both monitors.  On my office machine, I have 4 x 24" 1920x1200 monitors so the wallpapers I use for that are 3840x2400, as I stack two on top of two and not four across.
This screen size can be returned using a tool like xdpyinfo:
$ xdpyinfo | grep dimensions
  dimensions:    3840x2400 pixels (1016x635 millimeters)

It would be cool if the extension could figure this stuff out on it's own, but even if we were given some options to fill in our own minimum image size "dimension" and select the "wallpaper" or "zoom" option would work perfect for me. 

Thanks again for all the work you do on you gnome-shell extensions.

**Comment by neffo** [comment]
Unfortunately the images are static (and generated by Google for this [site](https://earthview.withgoogle.com/)), it's possible to generate new images through a different Google Maps [API](https://developers.google.com/maps/documentation/static-maps/intro) but the free version is limited to 640x640 images (paid version is 2048x2048, which is still not _quite_ enough for you, and Bing's equivalent service is 2000x1500).

I imagine the current image looks a bit ugly blown up to that resolution?
