### ISSUE TITLE
Can not install / can not enable

### ISSUE THREAD

**Issue by cyberbob4** [neffo/earth-view-wallpaper-gnome-extension#13]
I can not install the extension using the gnome extensions site. After I click install on button changes to off. I tried to install it from git. Now I can see the extension and settings but still cannot enable it. I guess a dependency is needed but can not find what it is? By the way Bing extension is working just fine.

**Comment by neffo** [comment]
There was a bug I introduced when I tried to add some new functionality. The current version also doesn't work with the latest version of GNOME (3.32), I've been looking at updating it but there is some outstanding issues. The data being fetched from Google is sometimes unreadable by the extension. I've not had a chance to work out the issue just yet, but will do my best in the next week.

**Comment by neffo** [comment]
@cyberbob4 Could you provide a bit of info about your setup? E.g. Linux distribution, version, etc?
