### ISSUE TITLE
Not work on Ubuntu18.04.03 LTS

### ISSUE THREAD

**Issue by JulianLian** [neffo/earth-view-wallpaper-gnome-extension#14]
system: Ubuntu 18.04.03 LTS
version: v9

After being installed and system reboot, it worked once. Nothing happened afterwards.

![image](https://user-images.githubusercontent.com/16442407/66692707-96934800-ecd3-11e9-93b6-7a541c4e4718.png)

**Comment by neffo** [comment]
Hi Julian,
