### ISSUE TITLE
West and East are flipped in location reporting

### ISSUE THREAD

**Issue by dllmr** [neffo/earth-view-wallpaper-gnome-extension#19]
![image](https://user-images.githubusercontent.com/7942204/75626627-f32ecb00-5bc0-11ea-8dd8-a82ed48a6a98.png)

E.g. this location should be reported as a western longitude rather than eastern. 

Looks like a simple change is needed in utils.js, i.e.

`function friendly_coordinates(lat, lon) {`
`  return Math.abs(lat).toFixed(4)+(lat>0 ? 'N': 'S')+', '+Math.abs(lon).toFixed(4)+(lon>0 ? 'E': 'W');`
`}`

**Comment by neffo** [comment]
Thanks for reporting the bug, it should be fixed in the git version, but if you are using the version from the GNOME extensions page it will take a little while to be updated.

**Comment by dllmr** [comment]
Thanks for the quick response - I'm loving the extension btw!
