### ISSUE TITLE
SyntaxError: illegal character

### ISSUE THREAD

**Issue by simonouel** [neffo/earth-view-wallpaper-gnome-extension#2]
Hi there great extension by the way!
Just to let you know that I installed it on centos 7.4, gnome 3.22 
I run the this commit: `aaed8e82d67a67071cea8c9a544de2afea69aafa`

All is working fine except the "Settings" is not openning and I have the error show up:
```
SyntaxError: illegal character

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
```
 
I didn't have the issue with the version 1

**Comment by neffo** [comment]
Hmm, I am not seeing that with Ubuntu 17.04 or Fedora 26. It's probably an issue with a strange apostrophe sneaking in to the code.

Can you share with me the output of this command?
`gjs $HOME/.local/share/gnome-shell/extensions/GoogleEarthWallpaper@neffo.github.com/prefs.js`

It may be related to the multi-line literal code starting at line 138. That is new, and I was probably being trying to be too clever.

**Comment by neffo** [comment]
Oh, it is the back ticks causing the problem.

String Template Literals were only added in Gnome 3.24. Whoops!
