### ISSUE TITLE
[BUG] Can't enable/disable indicator without re-enabling the extension 

### ISSUE THREAD

**Issue by motorto** [neffo/earth-view-wallpaper-gnome-extension#27]
**Describe the bug**
With this new update (version13), the toggle on settings to show/hide the indicator on bar seems to do nothing.

**To Reproduce**
1. Enable extension (the indicator should be enabled by default , on the first time, after installing )
2. Disable indicator ( it does nothing)
3. Disable Extension and Re-enable it (indicator is gone because of step 2)
4. Enable indicator (it does nothing as well)
5.  Repeat step 3 to get indicator enabled

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 34
 - Extension Version: 13
 - GNOME Version: 40.4

**Comment by neffo** [comment]
Thanks for the report, looking into this now.
