### ISSUE TITLE
Error: Value is not a valid 64-bit integer

### ISSUE THREAD

**Issue by sebas891** [neffo/earth-view-wallpaper-gnome-extension#3]
Hello,
Looks like a nice extension! Many thanks for the work.

I'm running Debian stretch 64bits with gnome 3.22.2, I just did a git clone, logout and login, when i click on "settings" I get this error.

```
Error: Value is not a valid 64-bit integer

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/overrides/Gtk.js:107
  buildPrefsWidget@/home/sebas/.local/share/gnome-shell/extensions/GoogleEarthWallpaper@neffo.github.com/prefs.js:61
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
```
Let me know if I can help debug that, I'm not a JS hacker.

Cheers,

Sébastien

**Comment by neffo** [comment]
Hmm, interesting. That was the first time you ran the extension, I presume?

**Comment by sebas891** [comment]
Yes the first time also everytimes I try to click on "Settings".  I try creating a new user and activating the extension and the same problem is there.

**Comment by neffo** [comment]
@sebas891 can you test the latest commit and let me know if it works? let me know if you see the map or not as well

(I had all kinds of trouble installing Debian 9 in a VM *glares at Gnome Boxes*)

**Comment by sebas891** [comment]
Everything is working! I can now see the "Settings" menu.  The menu "view in Google Maps"
Many thanks for the fix!

Cheers,
