### ISSUE TITLE
"View in Google Maps" displays map for old picture

### ISSUE THREAD

**Issue by NLSurfMan** [neffo/earth-view-wallpaper-gnome-extension#4]
Nitpick: using the v5 version, when you refresh the image **manually** and then click on "View in Google Maps", it will show you the map that was displayed **before** you clicked refresh and not the map of the currently showing image.

**Comment by neffo** [comment]
Hmm, I presume you have notifications off?

**Comment by neffo** [comment]
Clicking "View Description" (which creates a notification) fixes it.

**Comment by neffo** [comment]
This should be fixed in extension v6
