### ISSUE TITLE
link to install in README.md points to the wrong extension

### ISSUE THREAD

**Issue by NLSurfMan** [neffo/earth-view-wallpaper-gnome-extension#5]
The link under "Install from extensions.gnome.org" points to your _bing wallpaper changer_ instead of the _earth-view-wallpaper_ one. (I am not really familiar on how to create a pull request, otherwise I could have helped you out here :) )

**Comment by neffo** [comment]
Thanks, good pick up!

Of the two extensions this is the one I use - I prefer the imagery. The Bing one is more popular though... weird!
